- name: Data Domain NFS Configuration Playbook
  hosts: dd
  connection: local
  gather_facts: false
  vars_prompt:
    - name: share_name
      prompt: "Please enter the CIFS share name"
      private: false
    - name: delete_share_name
      prompt: "Please enter the CIFS share name to delete"
      private: false
  roles:
    - cifs_share_management # Role for managing CIFS shares
