- name: Data Domain NFS Configuration Playbook
  hosts: dd
  connection: local
  gather_facts: false

  vars_prompt:
    - name: user_input
      prompt: |
        Please select an action:
        1. Get CIFS status
        2. Check if a share exists
        3. Create a CIFS share
        4. Delete a CIFS share
      private: false

    - name: share_name
      prompt: "Please enter the CIFS share name to create"
      private: false
      default: ""  # Set a default value to handle unused prompts

    - name: delete_share_name
      prompt: "Please enter the CIFS share name to delete"
      private: false
      default: ""  # Set a default value to handle unused prompts

  roles:
    - cifs_share_management
