---
- name: Check if the share exists
  dellemc.datadomain.cifs:
    state: show
    share: "{{ share_name }}"
  register: share_check
  ignore_errors: true

- name: Show output of share_check
  ansible.legacy.debug:
    var: share_check
